{
 "title": "Go App",
 "description": "Count, Gauge, Histogram, and Summary for a demo go application in kubernetes",
 "time": { "from": "2024-05-14T06:56:23.950Z", "to": "2024-05-14T07:23:57.085Z" },
 "panels": [
  {
   "title": "Connected Devices(Gauge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "myapp_connected_devices", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Latency (Summary)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99, myapp_login_request_duration_seconds)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.90, myapp_login_request_duration_seconds)",
     "legendFormat": "P90"
    },
    {
     "expr": "quantile(0.5, myapp_login_request_duration_seconds)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency (Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method) (rate(myapp_request_duration_seconds_count[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(method) (rate(myapp_request_duration_seconds_count[1m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(method) (rate(myapp_request_duration_seconds_count[1m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "App Version(Gauge)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_info", "legendFormat": "{{version}}" }
   ]
  }
 ]
}