apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: go-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 5000
            - name: exporter-port
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-app-service
  name: go-app-service
spec:
  ports:
    - name: go-app-port
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: go-app
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    job: go-app
    app: go-app-exporter-service
  name: go-app-exporter-service
spec:
  ports:
    - name: go-app-exporter-port
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: go-app
  type: ClusterIP
